services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
      - sqlite_data:/code/db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  sqlite_data:
