# Generated by Django 5.2.1 on 2025-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
