# Generated by Django 5.2.1 on 2025-05-25 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_reservation_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
